package com.gmail.at.sichyuriyy.javatraining.homework1.rsa.cipher;

/**
 * Created by Yuriy on 02.02.2017.
 */
public interface RsaCipher {

    /**
     * @param data data to encrypt
     * @param key public key generated by
     *      {@link com.gmail.at.sichyuriyy.javatraining.homework1.rsa.keygenerator RsaKeyGenerator}
     * @return encrypted data
     * @see com.gmail.at.sichyuriyy.javatraining.homework1.rsa.keygenerator
     */
    byte[] encrypt(byte []data, RsaPublicKey key);


    /**
     * @param data data(encrypted earlier) to decrypt
     * @param key private key generated by
     *      {@link com.gmail.at.sichyuriyy.javatraining.homework1.rsa.keygenerator RsaKeyGenerator}
     * @return decrypted data
     * @see com.gmail.at.sichyuriyy.javatraining.homework1.rsa.keygenerator
     */
    byte[] decrypt(byte []data, RsaPrivateKey key);



}
